Build Frontend:
    image: node:20
    stage: Build
    before_script:
        - apt-get update
    after_script:
        - kill $(jobs -p) || true
    script:
        - npm ci
        - npm run build:pipeline
    artifacts:
        paths:
            - dist
        expire_in: 1 hour
    when: always
    tags:
        - hva
    rules:
        -   if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_ID

Deploy Frontend:
    image: node:20
    stage: Deploy
    before_script:
        - apt-get update
        - apt-get install -y lftp
        - apt-get install -y wget
    script:
        - >
            lftp -u $SFTP_WEB_USERNAME,$SFTP_WEB_PASSWORD -p $SFTP_WEB_PORT sftp://$SFTP_WEB_SERVERNAME -e "
            set sftp:auto-confirm yes;
            glob -a rm -r $ENVIRONMENT/wwwroot/*;
            mirror --reverse --verbose ./dist/web /$ENVIRONMENT/wwwroot;
            bye"
    after_script:
        - kill $(jobs -p) || true
    needs:
        - "Build Frontend"
    when: always
    rules:
        -   if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPLOY_WEB == "true"
            variables:
                ENVIRONMENT: "live"
        -   if: $CI_COMMIT_BRANCH == "develop" && $DEPLOY_WEB == "true"
            variables:
                ENVIRONMENT: "dev"
    tags:
        - hva
