Build Frontend:
    image: node:20
    stage: Build
    before_script:
        - apt-get update
        - apt-get install -y lftp
        - apt-get install -y wget
    after_script:
        - kill $(jobs -p) || true
    script:
        - npm ci
        - npm run build:pipeline
    artifacts:
        paths:
            - dist
        expire_in: 1 hour
    when: always
    tags:
        - hva
    rules:
        -   if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_ID
