Build Frontend:
    image: node:20
    stage: Build
    before_script:
        - apt-get update
    script:
        - npm ci
        - npm run build:frontend
        - npm run build:proxy
    after_script:
        - kill $(jobs -p) || true
    artifacts:
        paths:
            - dist
        expire_in: 1 hour
    when: always
    rules:
        -   if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_ID
    tags:
        - hva

Deploy Frontend:
    image: node:20
    stage: Deploy
    before_script:
        - apt-get update
        - apt-get install -y lftp
        - apt-get install -y wget
    script:
        - >
            lftp -u $SFTP_WEB_USERNAME,$SFTP_WEB_PASSWORD -p $SFTP_WEB_PORT sftp://$SFTP_WEB_SERVERNAME -e "
            set sftp:auto-confirm yes;
            glob -a rm -r $ENVIRONMENT/wwwroot/*;
            glob -a rm -r $ENVIRONMENT/app/*;
            mirror --reverse --verbose ./dist/web /$ENVIRONMENT/wwwroot;
            mirror --reverse --verbose ./dist/api /$ENVIRONMENT/app;
            bye"
    after_script:
        - kill $(jobs -p) || true
    needs:
        - "Build Frontend"
        - "Backend Unit Test"
    when: always
    rules:
        -   if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPLOY_WEB == "true"
            variables:
                ENVIRONMENT: "live"
        -   if: $CI_COMMIT_BRANCH == "develop" && $DEPLOY_WEB == "true"
            variables:
                ENVIRONMENT: "dev"
    tags:
        - hva

Deploy Screenshot Server:
    image: node:20
    stage: Deploy
    before_script:
        - apt-get update
        - apt-get install -y sshpass
    script:
        - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "rm -f node/index.js"
        - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "rm -f node/index.js.map"
        - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no ./dist/server/index.js $SSH_USER@$SSH_HOST:node/
        - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no ./dist/server/index.js.map $SSH_USER@$SSH_HOST:node/
        - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "./start_server.shh"
    after_script:
        - kill $(jobs -p) || true
    needs:
        - "Build Frontend"
        - "Backend Unit Test"
    when: always
    rules:
        -   if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPLOY_WEB == "true"
            variables:
                ENVIRONMENT: "live"
                SSH_USER: $SSH_USER_LIVE
                SSH_PASSWORD: $SSH_PASSWORD_LIVE
        -   if: $CI_COMMIT_BRANCH == "develop" && $DEPLOY_WEB == "true"
            variables:
                ENVIRONMENT: "dev"
                SSH_USER: $SSH_USER_DEV
                SSH_PASSWORD: $SSH_PASSWORD_DEV
    tags:
        - hva