version: '3.8'

services:
    db:
        image: mysql:8.0.20
        container_name: mysql8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: webshop
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - proxy

    init-db:
        image: node:20
        container_name: init-db
        working_dir: /usr/src/app
        entrypoint: [ "/usr/src/app/entrypoint.sh" ]
        volumes:
            - ./project/scripts:/usr/src/app
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - db
        networks:
            - proxy
        restart: 'no'

    frontend:
        build:
            context: ./project/frontend
        container_name: frontend
        working_dir: /usr/src/app
        volumes:
            - ./project/frontend:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        ports:
            - "3000:3000"
        expose:
            - "3000"
        depends_on:
            - db
        networks:
            - proxy
        user: "node"

    backend:
        build:
            context: ./project/backend
        container_name: backend
        working_dir: /home/gradle/project/backend
        volumes:
            - ./project/backend:/home/gradle/project/backend
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/webshop
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        ports:
            - "8080:8080"
        depends_on:
            - db
            - init-db
        networks:
            - proxy

volumes:
    db_data:
    node_modules:

networks:
    proxy:
