version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3306:3306"
    volumes:
      - mysql8:/var/lib/mysql
    networks:
      - proxy

volumes:
  mysql8:

networks:
  proxy:
