version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: mysql8
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        ports:
            - "3306:3306"
        volumes:
            - mysql8:/var/lib/mysql
        networks:
            - proxy

    init-db:
        image: node:20
        container_name: init-db
        working_dir: /usr/src/app
        entrypoint: [ "/usr/src/app/entrypoint.sh" ]
        volumes:
            - ./project/scripts:/usr/src/app
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - db
        networks:
            - proxy
        restart: 'no'

    frontend:
        image: node:20
        container_name: frontend
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run dev"
        volumes:
            - ./project/frontend:/usr/src/app
        ports:
            - "3000:3000"
        expose:
            - "3000"
        depends_on:
            - db
        networks:
            - proxy

    backend:
        image: gradle:7.3.3-jdk17
        container_name: backend
        working_dir: /home/gradle/project/backend
        command: sh -c "./gradlew clean build && ./gradlew bootRun"
        volumes:
            - ./project:/home/gradle/project
            - ./project/backend/.env:/home/gradle/project/.env
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:-mydatabase}
            SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-root}
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-root}
        ports:
            - "8080:8080"
        depends_on:
            - db
            - init-db
        networks:
            - proxy

volumes:
    mysql8:

networks:
    proxy:
