version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: mysql8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: webshop
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - proxy
volumes:
    db_data:

networks:
    proxy:
